name: 02 - Workflow Events

on: push

jobs:
  Show-the-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger name
        run: |
          echo "I've been triggered by a(n): ${{ github.event_name }} event."
